### ISSUE TITLE
Extension should only change the Z order of selected window

### ISSUE THREAD

**Issue by DarwinAwardWinner** [mattdavis90/overview-hover#2]
I've noticed a major usability issue with this extension: each window is focused immediately as soon as the mouse hovers over it, not when you exit the overview. Each time a window is focused, it is brought to the top of the window Z order stack. This means that if you activate the overview and then move the mouse across multiple windows, their Z order will now be defined by the order you hovered them, instead of how they were stacked before you entered the overview. 

The behavior I would expect is to leave the Z order alone except for bringing the one selected window to the front when you exit the overview.

**Comment by mattdavis90** [comment]
Hi, thanks for reporting this. I'm aware of this bug already. I've had a branch locally for a while that tries to implement this and your other issue but I just can't get the timing correct and the documentation for Gnome Extensions is awful. I've pushed my work-in-progress branch up so others can see - maybe someone with greater knowledge of the Gnome Shell internals can help. Sorry
