### ISSUE TITLE
Update metadata.json for Gnome 46

### ISSUE THREAD

**Issue by DarwinAwardWinner** [mattdavis90/overview-hover#3]
I've tested this extension in GNOME 46 (by manually editing the metadata file) and it seems to work unmodified.

**Comment by mattdavis90** [comment]
Oops, I thought I'd already done that. I'm not at my computer at the minute but I'll update it and create a new release. I've been running on gnome 46 since the fedora release and clearly forgot to push after testing.

**Comment by mattdavis90** [comment]
I've updated the metadata.json and the request to update on gnome.extensions is in
